#pragma once

#include "driver/gpio.h"
#include "driver/i2c_types.h"

#define DAY_I2C_SENSOR_PORT I2C_NUM_0
#define DAY_I2C_CAMERA_PORT I2C_NUM_1

#define DAY_PIN_USB_D_MINUS GPIO_NUM_19
#define DAY_PIN_USB_D_PLUS GPIO_NUM_20

#define DAY_PIN_I2C0_SDA GPIO_NUM_8
#define DAY_PIN_I2C0_SCL GPIO_NUM_9
#define DAY_PIN_IMU_INT GPIO_NUM_4

#define DAY_PIN_TF_CS GPIO_NUM_47
#define DAY_PIN_TF_MOSI GPIO_NUM_1
#define DAY_PIN_TF_MISO GPIO_NUM_2
#define DAY_PIN_TF_SCK GPIO_NUM_48

#define DAY_PIN_MIC_SCK GPIO_NUM_40
#define DAY_PIN_MIC_WS GPIO_NUM_41
#define DAY_PIN_MIC_SD GPIO_NUM_38

#define DAY_PIN_RGB_DIN GPIO_NUM_42
#define DAY_RGB_LED_COUNT 3

#define DAY_PIN_CAM_RST GPIO_NUM_3
#define DAY_PIN_CAM_SIOD GPIO_NUM_6
#define DAY_PIN_CAM_SIOC GPIO_NUM_7
#define DAY_PIN_CAM_MCLK GPIO_NUM_15
#define DAY_PIN_CAM_PCLK GPIO_NUM_16
#define DAY_PIN_CAM_VSYNC GPIO_NUM_17
#define DAY_PIN_CAM_HREF GPIO_NUM_18
#define DAY_PIN_CAM_D0 GPIO_NUM_10
#define DAY_PIN_CAM_D1 GPIO_NUM_11
#define DAY_PIN_CAM_D2 GPIO_NUM_12
#define DAY_PIN_CAM_D3 GPIO_NUM_13
#define DAY_PIN_CAM_D4 GPIO_NUM_14
#define DAY_PIN_CAM_D5 GPIO_NUM_21
#define DAY_PIN_CAM_D6 GPIO_NUM_39
#define DAY_PIN_CAM_D7 GPIO_NUM_45

#define DAY_SD_MOUNT_POINT "/sdcard"
#define DAY_RECORD_SECONDS 5
#define DAY_DEFAULT_WAKE_INTERVAL_SEC 300
